alertmanager:
  ## If false, alertmanager will not be installed
  ##
  enabled: false

kubeStateMetrics:
  ## If false, kube-state-metrics sub-chart will not be installed
  ##
  enabled: false

## kube-state-metrics sub-chart configurable values
## Please see https://github.com/kubernetes/kube-state-metrics/tree/master/charts/kube-state-metrics
##
# kube-state-metrics:

nodeExporter:
  ## If false, node-exporter will not be installed
  ##
  enabled: false

server:
  ## Prometheus server container name
  ##
  enabled: true

pushgateway:
  ## If false, pushgateway will not be installed
  ##
  enabled: false

## alertmanager ConfigMap entries
##
alertmanagerFiles:
  alertmanager.yml:
    global: {}
      # slack_api_url: ''

    receivers:
      - name: default-receiver
        # slack_configs:
        #  - channel: '@you'
        #    send_resolved: true

    route:
      group_wait: 10s
      group_interval: 5m
      receiver: default-receiver
      repeat_interval: 3h

## Prometheus server ConfigMap entries
##
serverFiles:

  prometheus.yml:

    scrape_configs:
      - job_name: prometheus
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['35.247.215.35:8080']
